module.exports = {
  apiAddress: 'http://api.hawk.qima-inc.com/',
  pages: [ { id: '1',
    core: '下单',
    service: 'order',
    method: 'wxpay_confirm',
    url: 'trade.koudaitong.com/wxpay/confirm',
    name: '支付页(收银台)' },
  { id: '2',
    core: '下单',
    service: 'order',
    method: 'confirm_index',
    url: 'trade.koudaitong.com/v2/trade/confirm/index',
    name: '支付跳转' },
  { id: '3',
    core: '下单',
    service: 'order',
    method: 'order_confirm',
    url: 'trade.koudaitong.com/v2/trade/order/confirm',
    name: '订单确认' },
  { id: '4',
    core: '物流',
    service: 'expreess',
    method: 'save_address',
    url: 'trade.koudaitong.com/trade/order/address.json',
    name: '保存地址' },
  { id: '5',
    core: '物流',
    service: 'expreess',
    method: 'selffetch_list',
    url: 'trade.koudaitong.com/v2/trade/selffetch/list.json',
    name: '到店自提list' },
  { id: '6',
    core: '物流',
    service: 'expreess',
    method: 'selffetch_book',
    url: 'trade.koudaitong.com/v2/trade/selffetch/book.json',
    name: '到店自提book' },
  { id: '7',
    core: '支付',
    service: 'pay',
    method: 'order_pay',
    url: 'trade.koudaitong.com/trade/order/pay.json',
    name: '支付操作' },
  { id: '8',
    core: '支付',
    service: 'pay',
    method: 'umpay_card',
    url: 'trade.koudaitong.com/pay/umpay/cards',
    name: '信用卡绑定' },
  { id: '9',
    core: '支付',
    service: 'pay',
    method: 'umpay_pay',
    url: 'trade.koudaitong.com/pay/umpay/confirm',
    name: '信用卡支付' },
  { id: '10',
    core: '支付',
    service: 'pay',
    method: 'umpay_agreeconfirm',
    url: 'trade.koudaitong.com/pay/umpay/agreeConfirm.json',
    name: '绑定确认' },
  { id: '11',
    core: '支付',
    service: 'pay',
    method: 'pay_baiduwap',
    url: 'trade.koudaitong.com/pay/baiduwap/redirect',
    name: '储蓄卡支付' },
  { id: '12',
    core: '交易结果页',
    service: 'order_result',
    method: 'baiduwap_return',
    url: 'trade.koudaitong.com/pay/baiduwap/return',
    name: '储蓄卡支付完成' },
  { id: '13',
    core: '交易结果页',
    service: 'order_result',
    method: 'order_complete',
    url: 'trade.koudaitong.com/trade/order/paid',
    name: '支付成功、失败中间页' },
  { id: '14',
    core: '交易结果页',
    service: 'order_result',
    method: 'confirm',
    url: 'trade.koudaitong.com/confirm',
    name: '结果页' },
  { id: '15',
    core: '交易结果页',
    service: 'order_result',
    method: 'order_result',
    url: 'wap.koudaitong.com/v2/trade/order/result',
    name: '订单详情页' },
  { id: '16',
    core: '交易结果页',
    service: 'order_result',
    method: 'order_express',
    url: 'wap.koudaitong.com/v2/trade/order/orderExpress.json',
    name: '获取物流信息' },
  { id: '17',
    core: '注册',
    service: 'sign_up',
    method: 'account',
    url: 'koudaitong.com/v2/account',
    name: '注册' },
  { id: '18',
    core: '注册',
    service: 'sign_up',
    method: 'smsg',
    url: 'koudaitong.com/v2/common/smsg/captcha.jsonp',
    name: '短信验证码' },
  { id: '19',
    core: '注册',
    service: 'login',
    method: 'company',
    url: 'koudaitong.com/v2/account/company/company.json',
    name: '获取公司信息' },
  { id: '20',
    core: '注册',
    service: 'login',
    method: 'team_solution',
    url: 'koudaitong.com/v2/account/team/solution',
    name: '选择推荐模板' },
  { id: '21',
    core: '注册',
    service: 'login',
    method: 'team_choose',
    url: 'koudaitong.com/v2/account/team/choose.json',
    name: '确认模板' },
  { id: '22',
    core: '注册',
    service: 'login',
    method: 'weixinbind',
    url: 'koudaitong.com/v2/account/auth/weixinbind',
    name: '微信绑定' },
  { id: '23',
    core: '注册',
    service: 'login',
    method: 'weixin_redirect',
    url: 'koudaitong.com/v2/weixin/component/redirecturi.json',
    name: '微信跳转' },
  { id: '24',
    core: '注册',
    service: 'login',
    method: 'url_create',
    url: 'wap.koudaitong.com/v2/common/url/create',
    name: '创建完成' },
  { id: '25',
    core: '登录',
    service: 'login',
    method: 'user_login',
    url: 'koudaitong.com/v2/account/user/login',
    name: '登录' },
  { id: '26',
    core: '登录',
    service: 'login',
    method: 'sso_login',
    url: 'login.youzan.com/sso/index/login.json',
    name: '登录' },
  { id: '27',
    core: 'wap登录',
    service: 'wap_login',
    method: 'auth_confirm',
    url: 'wap.koudaitong.com/v2/buyer/auth/authConfirm.json',
    name: 'wap登录' },
  { id: '28',
    core: 'wap登录',
    service: 'wap_login',
    method: 'auth_login',
    url: 'wap.koudaitong.com/v2/buyer/auth/authlogin.json',
    name: 'wap登录' },
  { id: '29',
    core: '商品市场选货',
    service: 'fenxiao',
    method: 'fenxiao_active_list',
    url: 'wap.koudaitong.com/v2/fenxiao/active/list',
    name: '微小店商品市场活动列表页' },
  { id: '30',
    core: '商品市场选货',
    service: 'fenxiao',
    method: 'fenxiao_goods',
    url: 'wap.koudaitong.com/v2/showcase_fenxiao/goods',
    name: '微小店非活动商品详情页' },
  { id: '31',
    core: '商品市场选货',
    service: 'fenxiao',
    method: 'fenxiao_goods_active',
    url: 'wap.koudaitong.com/v2/showcase_fenxiao/goods/active',
    name: '微小店活动商品详情页' },
  { id: '32',
    core: '商品市场选货',
    service: 'fenxiao',
    method: 'fenxiao_goods_create',
    url: 'wap.koudaitong.com/v2/fenxiao/goods/create.json',
    name: '微小店活动商品详情页添加到店铺后' } ]
};