module.exports = {
  apiAddress: 'http://api.hawk.qima-inc.com',
  pages: [ { id: '1',
    serviceName: '商品',
    service: 'goods',
    core: '下单',
    method: 'show_goods',
    url: 'detail.koudaitong.com/show/goods',
    name: '商品详情页' },
  { id: '2',
    serviceName: '下单',
    service: 'order',
    core: '下单',
    method: 'wxpay_confirm',
    url: 'trade.koudaitong.com/wxpay/confirm',
    name: '支付页(收银台)' },
  { id: '3',
    serviceName: '物流',
    service: 'expreess',
    core: '下单',
    method: 'save_address',
    url: 'trade.koudaitong.com/trade/order/address.json',
    name: '保存地址' },
  { id: '4',
    serviceName: '物流',
    service: 'expreess',
    core: '下单',
    method: 'selffetch_list',
    url: 'trade.koudaitong.com/v2/trade/selffetch/list.json',
    name: '到店自提list' },
  { id: '5',
    serviceName: '物流',
    service: 'expreess',
    core: '下单',
    method: 'selffetch_book',
    url: 'trade.koudaitong.com/v2/trade/selffetch/book.json',
    name: '到店自提book' },
  { id: '6',
    serviceName: '支付',
    service: 'pay',
    core: '下单',
    method: 'order_pay',
    url: 'trade.koudaitong.com/trade/order/pay.json',
    name: '支付操作' },
  { id: '7',
    serviceName: '支付',
    service: 'pay',
    core: '下单',
    method: 'umpay_card',
    url: 'trade.koudaitong.com/pay/umpay/cards',
    name: '信用卡绑定' },
  { id: '8',
    serviceName: '支付',
    service: 'pay',
    core: '下单',
    method: 'umpay_pay',
    url: 'trade.koudaitong.com/pay/umpay/confirm',
    name: '信用卡支付' },
  { id: '9',
    serviceName: '支付',
    service: 'pay',
    core: '下单',
    method: 'umpay_agreeconfirm',
    url: 'trade.koudaitong.com/pay/umpay/agreeConfirm.json',
    name: '绑定确认' },
  { id: '10',
    serviceName: '支付',
    service: 'pay',
    core: '下单',
    method: 'pay_baiduwap',
    url: 'trade.koudaitong.com/pay/baiduwap/redirect',
    name: '储蓄卡支付' },
  { id: '11',
    serviceName: '交易结果页',
    service: 'order_result',
    core: '下单',
    method: 'baiduwap_return',
    url: 'trade.koudaitong.com/pay/baiduwap/return',
    name: '储蓄卡支付完成' },
  { id: '12',
    serviceName: '交易结果页',
    service: 'order_result',
    core: '下单',
    method: 'order_complete',
    url: 'trade.koudaitong.com/trade/order/paid',
    name: '支付成功/失败中间页' },
  { id: '13',
    serviceName: '交易结果页',
    service: 'order_result',
    core: '下单',
    method: 'confirm',
    url: 'trade.koudaitong.com/confirm',
    name: '结果页' },
  { id: '14',
    serviceName: '交易结果页',
    service: 'order_result',
    core: '下单',
    method: 'order_result',
    url: 'trade.koudaitong.com/trade/order/result',
    name: '订单详情页' },
  { id: '15',
    serviceName: '交易结果页',
    service: 'order_result',
    core: '下单',
    method: 'order_express',
    url: 'trade.koudaitong.com/v2/trade/order/orderExpress.json',
    name: '获取物流信息' },
  { id: '16',
    serviceName: '登录',
    service: 'login',
    core: '登录',
    method: 'user_login',
    url: 'koudaitong.com/account/user/login',
    name: '登录（卖家）' },
  { id: '17',
    serviceName: '登录',
    service: 'login',
    core: '登录',
    method: 'sso_login',
    url: 'login.youzan.com/sso/index/login.json',
    name: '登录' },
  { id: '18',
    serviceName: 'wap登录',
    service: 'wap_login',
    core: '登录',
    method: 'auth_confirm',
    url: 'trade.koudaitong.com/v2/buyer/auth/authConfirm.json',
    name: '判断注册（买家）' },
  { id: '19',
    serviceName: 'wap登录',
    service: 'wap_login',
    core: '登录',
    method: 'auth_login',
    url: 'wap.koudaitong.com/v2/buyer/auth/authlogin.json',
    name: '进行登录（买家）' } ]
};